### PR TITLE
stage-2: Markup and JSX

### PR DESCRIPTION
**Pull request by MariaKonstantinov**
stage-2: initialize CRA

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for sending your project for review, it looks very good! I especially like your jsx and that all necessary items are interactive, I also like your adaptive layout on all screen resolutions - great job. I left several comments below and hope that they help you to improve your project and get more final points. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches with the mockup on 768 viewport https://pasteboard.co/ehDr2i8gA2BI.png https://pasteboard.co/tukiR180diYw.png https://pasteboard.co/EtytiywaYIvA.png
    * Mismatches with the mockup on 320 viewport https://pasteboard.co/eFJS0QFsA8XR.png
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Please don't use capital letter in `App` class name
    * You can't use modifier of modifier like `header__navigation_type_mobile_inactive`. Please fix all similar cases **throughout the project**
    * Modifier should also be used only with base selector, please check all modifiers in your project and make sure that all of them have base class from the modifier as well
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * News card booking button should have clicked state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * Logo, not found and preloader icons should be in svg format
- [ ]  Form elements should be highlighted when focused.
    * `popup__link` should have focus state
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 77

**Comment by MariaKonstantinov** [comment]
Hi, thank you very much for your review.

I am not sure I understand correctly this point: "Please don't use capital letter in App class name". Could you please advise? Thank you!

**Comment by MariaKonstantinov** [comment]
Hi!
Thank you for your review.
Regardign the review comments:
- News card booking button should have clicked state - it has a clicked state when logged in and hover state when not signed in (according to the design)

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm glad to accept your project! Btw you still can fix all the rest issues below and improve your project. Good luck on the next stage!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches with the mockup on 768 viewport https://pasteboard.co/ehDr2i8gA2BI.png https://pasteboard.co/tukiR180diYw.png https://pasteboard.co/EtytiywaYIvA.png
    * Mismatches with the mockup on 320 viewport https://pasteboard.co/eFJS0QFsA8XR.png
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * Logo, not found and preloader icons should be in svg format
- [ ]  Form elements should be highlighted when focused.
    * `popup__link` should have focus state
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 83

**Comment by MariaKonstantinov** [comment]
Thank you very much!

**Pull request merged**
